command_timeout = 2000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$nodejs\
$ruby\
$cmd_duration $time\
$line_break\
$character"""

[custom.gh_user]
when = true
command = "echo $(_gh_user)"
symbol = ""
format = "[$symbol $output]($style) "
require_repo = true

[nodejs]
style = "green"
format = "[$symbol($version)]($style) "

[ruby]
symbol = ""
format = "[$symbol ($version)]($style) "

[fill]
symbol = " "

[directory]
style = "yellow"
truncation_length = 3
truncate_to_repo = false

[character]
success_symbol = '[\$](purple)'
error_symbol = '[\$](bold red)'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = "[[$conflicted$untracked$modified$renamed$staged$deleted$stashed$ahead_behind](orange)]($style)"
conflicted = " $count "
untracked = " $count "
modified = " $count "
deleted = " $count "
staged = " $count "
renamed = " $count "
stashed = " $count "

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"
